sudo: required
services:
  - docker

before_install:
  - docker build -t gur79/react-test -f ./client/Dockerfile.dev ./client

script:
  -  docker run gur79/react-test npm test -- --coverage

after_success:
  - docker bulid -t gur79/multi-client ./client
  - docker build -t gur79/multi-nginx ./nginx
  - docker build -t gur79/multi-server ./server
  - docker build -t gur79/multi-worker ./worker
  #Log in to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take all these images and push them to Docker hub
  - docker push gur79/multi-client
  - docker push gur79/multi-nginx
  - docker push gur79/multi-server
  - docker push gur79/multi-worker